default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  # timeout est géré côté PG, pas besoin ici
  # En dev on peut se connecter en "peer" sans password

development:
  <<: *default
  database: <%= "#{Rails.application.class.module_parent_name.underscore}_development" %>

test:
  <<: *default
  database: <%= "#{Rails.application.class.module_parent_name.underscore}_test" %>

production:
  <<: *default
  # En prod, utilise DATABASE_URL (Render/Heroku) ou remplis ci-dessous
  url: <%= ENV["DATABASE_URL"] %>
  # Si tu n'as pas DATABASE_URL, tu peux renseigner :
  # host: <%= ENV["PGHOST"] %>
  # database: <%= ENV["PGDATABASE"] %>
  # username: <%= ENV["PGUSER"] %>
  # password: <%= ENV["PGPASSWORD"] %>
  # port: <%= ENV.fetch("PGPORT", 5432) %>
